<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>2614c4a1-1ce2-4993-a69e-86689e46ac20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is-search-input-62459</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is-search-input-62459']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec9fd191-751f-4158-a370-acdbd403eb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7eb3cc27-dd5f-4e1a-bebd-4a6b29a20f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is-search-input-62459</value>
      <webElementGuid>17e6cf38-51a5-4a95-afb3-23aca884fda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>9d546a14-382a-441e-814a-3939c8b5f726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-search-input</value>
      <webElementGuid>227bc03b-de73-4c2f-ac3b-df18685dd76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search here...</value>
      <webElementGuid>516789a3-394c-4284-accb-22ac080ec2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dd20c13c-6c6e-486c-8f4e-b0b37ea3fa1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is-search-input-62459&quot;)</value>
      <webElementGuid>3ba51c64-8b94-4290-86b7-2d6e7fa2ac95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is-search-input-62459']</value>
      <webElementGuid>64536566-767d-4281-ad16-1650da8d2c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='custom_html-3']/div[2]/form/label/input</value>
      <webElementGuid>6f0bcf66-ab43-4593-947e-8235ed1e0864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/label/input</value>
      <webElementGuid>7dd6fe9a-6f48-4e04-9abc-c1c7e0639727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'is-search-input-62459' and @name = 's' and @placeholder = 'Search here...']</value>
      <webElementGuid>97b853cf-e763-47b8-b599-a53f6656fabb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
